// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrItJuEVLNu2L3AfO8IVJ1A_LFbOKJkY4',
    appId: '1:919511123816:web:71e9919269f9cd8a35b8dd',
    messagingSenderId: '919511123816',
    projectId: 'donate-app10',
    authDomain: 'donate-app10.firebaseapp.com',
    storageBucket: 'donate-app10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6Hg2Dt9B2NHuqViDKTtDJMzkTEspJsw',
    appId: '1:919511123816:android:be2e7027d26fa79f35b8dd',
    messagingSenderId: '919511123816',
    projectId: 'donate-app10',
    storageBucket: 'donate-app10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYj2Weh0RqoEjWmhsb1eLKuPFxtHJ0ql4',
    appId: '1:919511123816:ios:ebc1ab6a729535af35b8dd',
    messagingSenderId: '919511123816',
    projectId: 'donate-app10',
    storageBucket: 'donate-app10.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrItJuEVLNu2L3AfO8IVJ1A_LFbOKJkY4',
    appId: '1:919511123816:web:44a0abd4a47c864a35b8dd',
    messagingSenderId: '919511123816',
    projectId: 'donate-app10',
    authDomain: 'donate-app10.firebaseapp.com',
    storageBucket: 'donate-app10.firebasestorage.app',
  );
}
